const TrackerData = {
  "overview": {
    "trainName": "The Ghan Expedition / Classic",
    "operator": "Journey Beyond Rail Expeditions",
    "totalDistanceKm": 2979,
    "durationHours": "Approx 54 hours (3 Days / 2 Nights)",
    "route": "Adelaide Parklands (SA) \u2192 Alice Springs (NT) \u2192 Katherine (NT) \u2192 Darwin Berrimah (NT)",
    "speed": "Average 85 km/h, max 115 km/h",
    "trainLength": "Typically 30-36 carriages (~800 metres long), hauled by two 4,400HP NR-class diesel-electric locomotives",
    "history": "Named in tribute to the pioneering 19th-century Afghan cameleers who forged trails into Australia's impassable red interior."
  },
  "mileposts": [
    {
      "km": 0,
      "name": "Adelaide Parklands Terminal",
      "state": "SA",
      "day": "Day 2",
      "time": "Morning (Depart 09:00 / 12:15)",
      "cellSignal": "Strong 5G/4G",
      "signalClass": "sig-high",
      "elevation": "50m",
      "notes": "Journey begins. Departure from the parklands surrounding South Australia's capital. Rolling plains of the Mid North.",
      "windowSight": "Adelaide Hills in the distance, expansive golden wheat fields and vineyards."
    },
    {
      "km": 135,
      "name": "Bowmans & Mid North Plains",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 10:45 AM",
      "cellSignal": "Moderate 4G",
      "signalClass": "sig-med",
      "elevation": "70m",
      "notes": "Rich agricultural belt. Crossing historic standard-gauge junctions.",
      "windowSight": "Wind turbines on the ridges, sweeping canola and barley paddocks."
    },
    {
      "km": 220,
      "name": "Port Pirie / Crystal Brook",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 12:15 PM",
      "cellSignal": "Good 4G",
      "signalClass": "sig-med",
      "elevation": "15m",
      "notes": "Major historic smelting port on the eastern shore of Spencer Gulf. The track nears the coast.",
      "windowSight": "First coastal views of Spencer Gulf and mangrove creeks."
    },
    {
      "km": 315,
      "name": "Port Augusta (The Crossroads)",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 02:00 PM",
      "cellSignal": "Strong 4G",
      "signalClass": "sig-high",
      "elevation": "10m",
      "notes": "Known as the 'Crossroads of Australia' where east-west (Indian Pacific) and north-south (The Ghan) rail corridors diverge.",
      "windowSight": "Towering red walls of the Southern Flinders Ranges (Mount Brown & Dutchmans Stern)."
    },
    {
      "km": 440,
      "name": "Bookaloo & Tent Hill",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 04:00 PM",
      "cellSignal": "Very Weak / Spotty",
      "signalClass": "sig-low",
      "elevation": "120m",
      "notes": "Landscape shifts dramatically from coastal plains to red clay pans and saltbush scrub. True outback begins.",
      "windowSight": "Flat-topped mesa hills (Tent Hills) glowing fiery ochre in the late afternoon sun."
    },
    {
      "km": 490,
      "name": "Pimba (Woomera Rocket Range Turnoff)",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 05:00 PM",
      "cellSignal": "Spotty 3G/4G",
      "signalClass": "sig-low",
      "elevation": "145m",
      "notes": "Pimba is the rail siding for the Woomera Prohibited Area, the world's largest land-based weapons testing range (122,000 sq km).",
      "windowSight": "Spuds Roadhouse iconic sign, expansive dry salt lakes (Island Lagoon & Lake Hart)."
    },
    {
      "km": 540,
      "name": "Lake Hart (Salt Lake Siding)",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 05:45 PM",
      "cellSignal": "No Service",
      "signalClass": "sig-none",
      "elevation": "110m",
      "notes": "A massive, glistening white salt pan extending across the horizon. Used for salt harvesting in the early 20th century.",
      "windowSight": "Blinding white salt crust contrasting with deep red desert sand dunes. Golden hour magic."
    },
    {
      "km": 725,
      "name": "Kingoonya & Tarcoola Junction",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 08:30 PM",
      "cellSignal": "No Service",
      "signalClass": "sig-none",
      "elevation": "160m",
      "notes": "Tarcoola is the historic junction where the Trans-Australian Railway heads west across the Nullarbor to Perth, while The Ghan turns north into the interior.",
      "windowSight": "Remote rail sidings illuminated by train lights."
    },
    {
      "km": 880,
      "name": "Manguri (Coober Pedy Siding)",
      "state": "SA",
      "day": "Day 2",
      "time": "Approx 10:45 PM",
      "cellSignal": "Weak / None",
      "signalClass": "sig-none",
      "elevation": "180m",
      "notes": "Located 42km west of Coober Pedy, the underground opal mining capital of the world. Remote desert silence.",
      "windowSight": "Endless moonlit plains, desert night sky with crystalline clarity."
    },
    {
      "km": 1060,
      "name": "Marla Siding (Outback Dawn)",
      "state": "SA",
      "day": "Day 3",
      "time": "Approx 05:45 AM - 07:15 AM",
      "cellSignal": "Telstra 4G in Siding",
      "signalClass": "sig-low",
      "elevation": "310m",
      "notes": "Dawn stop in remote northern SA. Passengers step down onto desert earth for freshly brewed coffee and bacon rolls around trackside firepits.",
      "windowSight": "Spectacular sunrise over desert mulga trees and spinifex. Watch sky turn violet, gold, and crimson."
    },
    {
      "km": 1300,
      "name": "Kulgera & SA / NT Border",
      "state": "NT",
      "day": "Day 3",
      "time": "Approx 10:00 AM",
      "cellSignal": "No Service",
      "signalClass": "sig-none",
      "elevation": "490m",
      "notes": "The Ghan crosses the 26th parallel south, officially entering the Northern Territory. Kulgera is the southernmost pub in the NT.",
      "windowSight": "Deep red 'bull-dust' desert roads, desert oaks with weeping grey-green foliage."
    },
    {
      "km": 1450,
      "name": "Finke River Crossing (Henbury)",
      "state": "NT",
      "day": "Day 3",
      "time": "Approx 11:45 AM",
      "cellSignal": "No Service",
      "signalClass": "sig-none",
      "elevation": "430m",
      "notes": "Ancient river system carved through the Amadeus Basin. Geologists estimate the Finke has flowed in its current meandering course for 350+ million years.",
      "windowSight": "Broad sandy riverbed lined by ancient ghost gums and river red gums."
    },
    {
      "km": 1555,
      "name": "Alice Springs Railway Station",
      "state": "NT",
      "day": "Day 3",
      "time": "01:45 PM - 10:00 PM (Extended Stop)",
      "cellSignal": "Strong 5G/4G",
      "signalClass": "sig-high",
      "elevation": "575m",
      "notes": "The Red Centre capital nestled in a natural gap in the MacDonnell Ranges (Heavitree Gap). Major off-train excursions and Outback BBQ.",
      "windowSight": "Dramatic red quartzite ramparts of the MacDonnell Ranges towering over the town."
    },
    {
      "km": 1830,
      "name": "Barrow Creek Siding",
      "state": "NT",
      "day": "Day 3/4",
      "time": "Approx 02:00 AM (Overnight)",
      "cellSignal": "No Service",
      "signalClass": "sig-none",
      "elevation": "500m",
      "notes": "Historic 1872 Overland Telegraph Station outpost. Site of frontier conflicts and communications backbone.",
      "windowSight": "Night rail traversal."
    },
    {
      "km": 1950,
      "name": "Karlu Karlu / Devils Marbles Vicinity",
      "state": "NT",
      "day": "Day 4",
      "time": "Approx 04:00 AM",
      "cellSignal": "Spotty 3G",
      "signalClass": "sig-low",
      "elevation": "410m",
      "notes": "Sacred Warumungu and Kaytetye site featuring giant rounded granite boulders precariously balanced across the valley.",
      "windowSight": "Pre-dawn desert horizon."
    },
    {
      "km": 2050,
      "name": "Tennant Creek",
      "state": "NT",
      "day": "Day 4",
      "time": "Approx 05:30 AM",
      "cellSignal": "Good 4G in town",
      "signalClass": "sig-med",
      "elevation": "375m",
      "notes": "Australia's last great 1930s gold rush town, located at the junction of the Stuart and Barkly Highways.",
      "windowSight": "Sunrise over the Barkly Tablelands grasslands."
    },
    {
      "km": 2300,
      "name": "Newcastle Waters & Dunmarra",
      "state": "NT",
      "day": "Day 4",
      "time": "Approx 07:30 AM",
      "cellSignal": "No Service",
      "signalClass": "sig-none",
      "elevation": "230m",
      "notes": "Heart of legendary outback cattle stations spanning millions of acres (such as Brunette Downs and Newcastle Waters).",
      "windowSight": "Transition from arid desert to subtropical savannah grasslands and cattle mobs."
    },
    {
      "km": 2665,
      "name": "Katherine Station (Nitmiluk)",
      "state": "NT",
      "day": "Day 4",
      "time": "09:00 AM - 01:00 PM (Excursion Stop)",
      "cellSignal": "Strong 4G",
      "signalClass": "sig-high",
      "elevation": "108m",
      "notes": "Gateway to Nitmiluk National Park where 13 gorges have been carved through sheer sandstone by the Katherine River. Jawoyn traditional lands.",
      "windowSight": "Lush tropical pandanus palms, broad flowing rivers, rugged gorge escarpments."
    },
    {
      "km": 2755,
      "name": "Pine Creek",
      "state": "NT",
      "day": "Day 4",
      "time": "Approx 02:45 PM",
      "cellSignal": "Weak 4G",
      "signalClass": "sig-low",
      "elevation": "205m",
      "notes": "1871 gold boom town. Built largely by Chinese immigrant miners who stayed after building the original narrow-gauge railway.",
      "windowSight": "Historic station buildings, giant cathedral termite mounds towering 4-5m high."
    },
    {
      "km": 2870,
      "name": "Adelaide River",
      "state": "NT",
      "day": "Day 4",
      "time": "Approx 04:15 PM",
      "cellSignal": "Moderate 4G",
      "signalClass": "sig-med",
      "elevation": "52m",
      "notes": "WWII headquarters and war cemetery following the 1942 bombing of Darwin. Famous wetlands filled with wildlife.",
      "windowSight": "Expansive tropical floodplains, water buffalo, and towering bamboo clusters."
    },
    {
      "km": 2979,
      "name": "Darwin Berrimah Terminal",
      "state": "NT",
      "day": "Day 4",
      "time": "Evening Arrival (05:30 PM / 07:50 PM)",
      "cellSignal": "Strong 5G/4G",
      "signalClass": "sig-high",
      "elevation": "30m",
      "notes": "The northern terminus of The Ghan. The line was completed in 2004, finally connecting Australia from south to north.",
      "windowSight": "Darwin harbour glimpses, tropical palms, and the warm breeze of the Timor Sea."
    }
  ],
  "trainLife": {
    "power": "Standard Australian 3-pin Type I power points (240V AC, 50Hz) in all Gold & Platinum cabins. Bring an AU plug adapter or USB multi-charger. Low-wattage appliances only (chargers, CPAP, laptops; high-draw appliances like hair dryers use provided salon outlets).",
    "connectivity": "There is NO on-train Wi-Fi. Mobile reception exists only near major towns (Port Augusta, Alice Springs, Tennant Creek, Katherine, Darwin). Expect ZERO cell coverage for roughly 75% of the 54-hour journey. Download all guides, books, and podcasts beforehand.",
    "dining": "Meals in the Queen Adelaide Restaurant are served in two seatings (Early and Late). Carriage attendants will ask your preferred seating time each morning. All beverages (except ultra-rare reserve cellar wines) are included in Gold/Platinum fares.",
    "dressCode": "Daytime: Casual, breathable resort wear, sturdy flat shoes for moving between carriages. Dinner: Smart-casual (neat trousers/collared shirt/dress; no athletic singlets or flip-flops in dining car). Excursions: Hiking/walking shoes, sun hat, sunglasses, fly net.",
    "luggage": "Checked luggage (up to 2x 25kg bags per person) is stored in the luggage van and CANNOT be accessed en route. Only hand luggage / daypack is permitted in your cabin due to space efficiency."
  }
};
